### ISSUE TITLE
ELE plugin missing, not active, or inaccessible to patcher!

### ISSUE THREAD

**Issue by qualityassuance** [Benna96-Synthesis/ELE_Patcher#1]
Running ELE patcher through Synthesis gives me this error no matter what version I use. Here's the full log:

Compiling
No extra data to consider
("C:\Users\kkear\AppData\Local\Temp\Synthesis\3fo2rdsx.slt\Git\njcyta2t.o5e\Runner\ELE_Patcher"): "dotnet" "build \"ELE_Patcher.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "1604ac05a43fec6f3e2137e336d49e9259590d84"
Running
(""): "dotnet" "run --project \"C:\Users\kkear\AppData\Local\Temp\Synthesis\3fo2rdsx.slt\Git\njcyta2t.o5e\Runner\ELE_Patcher\ELE_Patcher.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath \"C:\Modlists\Game Folder for Serenity\Skyrim Special Edition\Data\" --ExtraDataFolder \"C:\Modlists\Serenity\tools\Synthesis .23 6-1\Data\Skyrim Special Edition\ELE_Patcher\" --GameRelease SkyrimSE --ModKey Synthesis3.esp --LoadOrderFilePath C:\Users\kkear\AppData\Local\Temp\Synthesis\3fo2rdsx.slt\Workspace\Synthesis3\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\kkear\AppData\Local\Temp\Synthesis\3fo2rdsx.slt\Workspace\Synthesis3\1 - ELE_Patcher\Synthesis3.esp\" --PatcherName ELE_Patcher"
Mutagen version: 0.33.5
Mutagen sha: d23e0cae9fb1fb6114db1ee56945638a735f3f06
Synthesis version: 0.20.5
Synthesis sha: 34cd545124be0cf01d98cd2f1d75f30d500c8a5b
run-patcher --DataFolderPath "C:\Modlists\Game Folder for Serenity\Skyrim Special Edition\Data" --ExtraDataFolder "C:\Modlists\Serenity\tools\Synthesis .23 6-1\Data\Skyrim Special Edition\ELE_Patcher" --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\kkear\AppData\Local\Temp\Synthesis\3fo2rdsx.slt\Workspace\Synthesis3\Plugins.txt --OutputPath "C:\Users\kkear\AppData\Local\Temp\Synthesis\3fo2rdsx.slt\Workspace\Synthesis3\1 - ELE_Patcher\Synthesis3.esp" --PatcherName ELE_Patcher
Checking runnability
Checking runnability complete
Prepping state.
Reading settings: C:\Modlists\Serenity\tools\Synthesis .23 6-1\Data\Skyrim Special Edition\ELE_Patcher\settings.json

Patching records from ELE_SSE.esp:
- Image spaces
MissingModException ELE_SSE.esp: 

ELE plugin missing, not active, or inaccessible to patcher!

    at Mutagen.Bethesda.HasModsMixIn.AssertHasMod(ILoadOrderGetter`1 loadOrder, ModKey modKey, Nullable`1 enabled, String message)
   at ELE_Patcher.Program.<>c.<Main>b__2_0(IRunnabilityState state) in C:\Users\kkear\AppData\Local\Temp\Synthesis\3fo2rdsx.slt\Git\njcyta2t.o5e\Runner\ELE_Patcher\Program.cs:line 33
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass15_0.<<AddRunnabilityCheck>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 113
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.CheckRunnability(CheckRunnability args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 146System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at ELE_Patcher.Utility.Util.InitializeRecordVars[T,TGetter](TGetter modRecord, IPatcherState`2 state, ModKey modKey, HashSet`1 masters, HashSet`1& vanillaRecords, T& patched, Boolean& changed, HashSet`1 knownPatches) in C:\Users\kkear\AppData\Local\Temp\Synthesis\3fo2rdsx.slt\Git\njcyta2t.o5e\Runner\ELE_Patcher\Utility\Util.cs:line 65
   at ELE_Patcher.Program.PatchVanilla(IPatcherState`2 state) in C:\Users\kkear\AppData\Local\Temp\Synthesis\3fo2rdsx.slt\Git\njcyta2t.o5e\Runner\ELE_Patcher\Program.cs:line 57
   at ELE_Patcher.Program.RunPatch(IPatcherState`2 state) in C:\Users\kkear\AppData\Local\Temp\Synthesis\3fo2rdsx.slt\Git\njcyta2t.o5e\Runner\ELE_Patcher\Program.cs:line 40
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 101
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 507
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 428
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 400
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 52
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 52
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 65
   at Synthesis.Bethesda.Execution.Running.Runner.RunSomePatchers.Run(IGroupRun groupRun, PatcherPrepBundle[] patchers, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunSomePatchers.cs:line 36
   at Synthesis.Bethesda.Execution.Running.Runner.RunAGroup.Run(IGroupRun groupRun, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAGroup.cs:line 59
   at Synthesis.Bethesda.Execution.Running.Runner.RunAllGroups.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAllGroups.cs:line 36
   at Synthesis.Bethesda.Execution.Running.Runner.ExecuteRun.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\ExecuteRun.cs:line 54
   at Synthesis.Bethesda.GUI.Services.Profile.Running.ExecuteGuiRun.Run(IEnumerable`1 groupRuns, PersistenceMode persistenceMode, Boolean localize, Language targetLanguage, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\Services\Profile\Running\ExecuteGuiRun.cs:line 49
   at Synthesis.Bethesda.GUI.ViewModels.Profiles.Running.RunVm.<Run>b__39_1(Unit _) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\ViewModels\Profiles\Running\RunVm.cs:line 200

**Comment by Noggog** [comment]
Sounds like https://github.com/Mutagen-Modding/Synthesis/discussions/243
